server:
  port: 9008
  servlet:
    context-path: /record-account

#server 地址
remote:
#  ip: 192.168.1.134
  ip: 127.0.0.1
  user-port: 10003
  record-account-port: 10004


# rest 风格参数配置 (用在HttpUtil中)
rest:
  connection:
    # 建立超时时间 单位ms
    connect-timeout: 15000
    # 建立连接成功后 从服务器读取超时时间 单位ms
    read-timeout: 15000

# JWT 配置
jwt:
  # 登录有效时间 单位 （h）
  login-timeout: 30
  # 公钥
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtxJuPRMyxZF7rSWBi6JY6ULSWo+/l2gd+Ap7a6VVuSHWGM8PQaVNmXKp2L1ythAAlSJL5Xjv/ZWI89UST3u9OGB8GcYatcn0Znjej+Ju2yaXPu8s5SEfnlOGgxbIlhOxQVk4YYk85/jOHgKQ2Hm5YIL1KEmDdpLvAPAVWTiPU8tNjNAoEMFQNfZKuI/cJsn8jHfsWXwXtcXTzwcVT3WJiNCOEzmaED0UsMV7hQ8vXFdoZR57xIz1uHUgvdVKazb69ODZo9Pw7nWt129QTEmafnjuqrMRzxsQLgCHJJmqqy7eNF0MNFR7GNH9FtMw+OG5g4jodreSYUwePpOYAh6CCwIDAQAB
  # 私钥
  private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC3Em49EzLFkXutJYGLoljpQtJaj7+XaB34CntrpVW5IdYYzw9BpU2ZcqnYvXK2EACVIkvleO/9lYjz1RJPe704YHwZxhq1yfRmeN6P4m7bJpc+7yzlIR+eU4aDFsiWE7FBWThhiTzn+M4eApDYeblggvUoSYN2ku8A8BVZOI9Ty02M0CgQwVA19kq4j9wmyfyMd+xZfBe1xdPPBxVPdYmI0I4TOZoQPRSwxXuFDy9cV2hlHnvEjPW4dSC91UprNvr04Nmj0/Duda3Xb1BMSZp+eO6qsxHPGxAuAIckmaqrLt40XQw0VHsY0f0W0zD44bmDiOh2t5JhTB4+k5gCHoILAgMBAAECggEBAKm4L3T1mGsq3aJ+k+O0xYKyzTrh6zfdcXMjnJoGNDumj8p+I2GzcwZgE+/4aiE5IqEfo4cAoFTSTZ3nmcsQJzLd2A845khECwz43zQ7MpR+6VaR+2gMVji8rIZZF+pyJTE1Gpzp0wonUkbmEAxwhJhhsBACXxsNSv/uk4wccFu4G8MbtciM7sy5jrmowRZVHX8jE7ZOOwMPi7Vs333nduAQ6FTqjMYMXKxTZPSOYiq9znAyuNZaJ3ooDO8YSnjsTTwv15JclqPNLcOzBLnmZYPYHkGM8TfulbmEOeemLR64jI12ttsQnh/wQAWLnArhVNIsoZjQdTbFORhG8KxlWhECgYEA4pHoz1d32uFh1Vay92MfoSI7Xzx3dpGmv42ymo/xx04Zg6CSXPFMv+OoXDRpyKktxAunBIseju+b+4I0dGuz0p8ZILp4omwATvkDNRfZFGhZq6dNFis2OPACQyVmz3XSlMdPuo1JyCociZJD7p/DEWffp+XsSf/gEXzk54WvBpMCgYEAztoXVJfr3/edpocXZR637fSY5A60fc9DZGAJG89xIbjWu65rC8C9tzAbB/9ohGVoH5G5h3VrQkpCd0LHE0hbO+I5dExGx0nCEiQy6Qwv+a7VcecOt8/MqkZzLzZQsFpx6M1DGUsn5udZtfLlYo3Zp0E6E1pRQm0IW9zwfNtICakCgYBuCXktQgjWyAFw0GOo3H5fDrYRIdfPQRvgClyEzoYZSuf/UnvjIdopk9KPvXDm4Kt2fEZIYZycxOhXtTvukuRJ1bUpfQbbs2JO+IdDQOrQC4IJaP56VtBFxOMEY2TUOx/j3AzvyHDeAv3LHrtZaEQf7vfjnjotElVriOHPQ9DmewKBgAKgQiuQwi3VtuqmTGW8PhmHQWmjxibSushLb9IqkAUdk5xOWo2LpNzuf2lalLkZkHjWIMTXeMUerDlXX6+e+4mHFbOkREHDbfNNAlhzDyjcT1li1Yz/1llTC6NNzThv7YJHGNL5YUhNJ5ZnvwHBS0IUUehs/Rsax0BjTapIHmIBAoGBAMsqLvDaFrzX1ep3IZZKXC2hlFVh+pX0EUprd2QsF6Hs+jxlAV5kIh/jGnUO64cmRvjYUPP75vTlaiBbe8w666CqMrCZSgum/4QbtofMOrda4YggQ+aSJkUjhEJgwciO9CG29+9lCgJPNUIneH6p/TGz1RKFt+FwvjiZ0QkPVhPF

